enum ActionType {
    UPDATE_SIGN_IN_STATUS,
    SET_FILE_ID,
    CTRL_CLICK,
    SHIFT_CLICK,
    SINGLE_CLICK,
    PARSE_DATA,
    SET_NAME,
    CLEAR_SELECTION,
    PAINT,
    ERASE,
    ADD_QUEUE,
    REMOVE_QUEUE,
    MARK_READY,
    MARK_SAVED,
    SET_COLORS,
    FAIL,
    SET_LEVEL_TIME,
    SET_CANVAS_BASE_TIME,
    SET_CANVAS_PER_COLOR_TIME,
}

export default ActionType;
